"""add candidate_id to entities

Revision ID: 52be06c3b3cb
Revises: 34353f36e11f
Create Date: 2026-07-22 09:29:01.470116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52be06c3b3cb'
down_revision: Union[str, Sequence[str], None] = '34353f36e11f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('candidate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entities', 'candidates', ['candidate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_column('entities', 'candidate_id')
    # ### end Alembic commands ###
