"""add phone_number to candidates

Revision ID: e26d61b5eb2f
Revises: fc8824bc6af0
Create Date: 2026-07-18 11:51:44.308997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26d61b5eb2f'
down_revision: Union[str, Sequence[str], None] = 'fc8824bc6af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'phone_number')
    # ### end Alembic commands ###
